# Trading Agent Configuration

# Data Settings
data:
  symbols: ["AAPL", "GOOGL", "MSFT", "TSLA"]
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  train_split: 0.8
  lookback_window: 20

# Environment Settings
environment:
  initial_balance: 10000
  transaction_cost: 0.001  # 0.1% per trade
  max_position: 1.0  # Maximum position size (100% of portfolio)
  reward_scaling: 1.0

# Technical Indicators
indicators:
  - "SMA_10"
  - "SMA_20"
  - "RSI_14"
  - "MACD"
  - "BB_upper"
  - "BB_lower"
  - "volume_sma"

# Model Architecture
model:
  hidden_layers: [256, 128, 64]
  activation: "relu"
  dropout: 0.2

# Training Parameters
training:
  episodes: 1000
  batch_size: 32
  learning_rate: 0.0001
  gamma: 0.95  # Discount factor
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  memory_size: 10000
  target_update: 100

# Evaluation
evaluation:
  test_episodes: 10
  save_plots: true
  metrics: ["total_return", "sharpe_ratio", "max_drawdown", "win_rate"]
